### ISSUE TITLE
Can I lrun this project in ROS kinetic?

### ISSUE THREAD

**Issue by Conearth** [stevenliu216/demo_lidar#1]
Hello Steven.
I use ROS kinetic and Opencv3 , and when I tried to configure the project, errors occurred. So ,what should I do to make this project can run in Kinetic ? Does this project can only run under Indigo and Opencv2?
Looking forward to your reply.

**Comment by stevenliu216** [comment]
Hi,

You can see the original [documentation](http://wiki.ros.org/demo_lidar) on ROS wiki. It shows the project only runs on indigo and opencv2. 

To get it running on kinetic, you have to compile your own version of opencv3 with extra contrib modules.  Between opencv2 and opencv3, many files were shuffled around so every #include need to be updated in the source code. If you're a beginner with opencv this might take a while to figure out.

**Comment by Conearth** [comment]
Hi Steven！

     I'm a master of Beihang university. My name is Kong. I'm so appreciated your attention to this message. 
     I saw the "demo_lidar" you published on GitHub. Are you doing research related with Lidar-SLAM？Now I am researching on this field and looking for some laser and visual fusion SLAM algorithm to go on my study.. Do you have the codes for V-LOAM？I would be very grateful if you could provide the codes of V-LOAM or other laser-visual algorithms. I can even provide some compensation if needed. 
     Looking forward to your reply. 
                                                                                                                                           Best regards .

**Comment by Conearth** [comment]
Hi Steven！

I'm a master of Beihang university. My name is Kong. I'm so appreciated your attention to this message. 
I saw the "demo_lidar" you published on GitHub. Are you doing research related with Lidar-SLAM？Now I am researching on this field and looking for some laser and visual fusion SLAM algorithm to go on my study.. Do you have the codes for V-LOAM？
I would be very grateful if you could provide the codes of V-LOAM or other laser-visual algorithms. I can even provide some compensation if needed. 
Looking forward to your reply. 
                                                  Best regards .

**Comment by stevenliu216** [comment]
Kong, you can contact V-LOAM's original authors for the code. They are helpful if you're clear that it's for research purposes.

**Comment by Conearth** [comment]
OK.Thanks anyway:)
